apiVersion: v1
kind: Service
metadata:
  name: {{ include "control-plane.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      name: http