"""Run-config generator — run.<id>.toml with a relative scope_file (docs/conductor.md §7 [3]).

The one subtlety (§3.2): the harness resolves `[target].scope_file` relative to
the run.toml's OWN directory, not the cwd. So the generated toml is written into
the same out-dir as the emitted scope.yaml and sets a bare basename, never an
absolute path. Self-validated by re-opening with tomllib and asserting the shape
the harness's `load_config` will see (docs/conductor.md C1).
"""

from __future__ import annotations

import tomllib
from pathlib import Path

from autosploit_conductor.context import ConductorError, EngagementContext

# Model/budget defaults (docs/conductor.md §4 [3]): DeepSeek flash / high /
# empty fallbacks for eval-style attribution, generous caps.
_MODEL_ID = "deepseek/deepseek-v4-flash"
_REASONING = "high"
_FALLBACKS: tuple[str, ...] = ()
_MAX_USD = 5.0
_MAX_TOKENS = 2_000_000
_MAX_TOOL_CALLS = 60


class ConfigGenError(ConductorError):
    """Run-config generation failed (bad scope path or self-validation)."""


def write_run_config(context: EngagementContext, scope_path: Path) -> Path:
    """Write `run.<id>.toml` next to `scope_path` and return its path (C1).

    The toml lives in the same dir as the scope file so the relative
    `scope_file` resolves correctly, and `[output].dir` points at the
    engagement's own `runs/` subdir. The file is parsed back with tomllib and
    the shape the harness requires is asserted before returning.
    """
    scope_path = Path(scope_path)
    scope_dir = scope_path.parent

    if not scope_path.exists():
        raise ConfigGenError(f"scope file not found: {scope_path}")

    run_toml = scope_dir / f"run.{context.engagement_id}.toml"
    output_dir = context.out_dir / "runs"

    run_toml.write_text(
        _render(context, scope_path.name, output_dir.as_posix()),
        encoding="utf-8",
    )

    _validate(run_toml, scope_path.name)
    return run_toml


def render_run_config(
    context: EngagementContext, scope_basename: str, output_dir: str
) -> str:
    """Return the run.toml text (no disk write) — the ConfigMap payload for Phase B.

    Phase A writes run.toml to the out-dir (`write_run_config`); Phase B mounts it
    from a ConfigMap, so the k8s provisioner needs the text, not a file. Same
    renderer, so both paths stay in lockstep. `scope_basename` is the sibling
    scope file's bare name (mounted next to run.toml); `output_dir` is a Pod-local
    path the harness writes its report into."""
    return _render(context, scope_basename, output_dir)


def _render(context: EngagementContext, scope_basename: str, output_dir: str) -> str:
    """Render the run.toml text. `scope_file` is the bare basename (§3.2);
    `output_dir` is a POSIX-style path so it round-trips through TOML on Windows.
    """
    fallbacks = ", ".join(f'"{f}"' for f in _FALLBACKS)
    return f"""\
# Run config generated by the conductor (docs/conductor.md §4 [3]).
# Consumed by the harness CLI (Seam B): autosploit-harness run --config <this file>.

[model]
id = "{_MODEL_ID}"
reasoning = "{_REASONING}"
fallbacks = [{fallbacks}]

[budget]
max_usd = {_MAX_USD}
max_tokens = {_MAX_TOKENS}
max_tool_calls = {_MAX_TOOL_CALLS}

[target]
scope_file = "{scope_basename}"

[output]
dir = "{output_dir}"
"""


def _validate(run_toml: Path, scope_basename: str) -> None:
    """Self-validate: re-open with tomllib, assert the harness-required shape."""
    try:
        parsed = tomllib.loads(run_toml.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as exc:  # pragma: no cover - render is static
        raise ConfigGenError(f"generated run config does not parse: {exc}") from exc

    model = parsed.get("model", {})
    budget = parsed.get("budget", {})
    target = parsed.get("target", {})
    output = parsed.get("output", {})

    if not model.get("id"):
        raise ConfigGenError(f"{run_toml}: [model].id is required")
    if target.get("scope_file") != scope_basename:
        raise ConfigGenError(
            f"{run_toml}: [target].scope_file must be the bare basename "
            f"{scope_basename!r}, not an absolute path"
        )
    if not output.get("dir"):
        raise ConfigGenError(f"{run_toml}: [output].dir is required")
    if not all(isinstance(budget.get(k), (int, float)) for k in ("max_usd", "max_tokens", "max_tool_calls")):
        raise ConfigGenError(f"{run_toml}: [budget] caps must be numeric")
